---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfs-deployment
  labels:
    app: myapp
    scope: testing
  namespace: nancy-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myap
    spec:
      containers:
        - name: myapp-container
          image: harbor.nancy.rid-intrasoft.eu/tfs/myapp:latest
          ports:
            - containerPort: 8000
          command:
            [
              "gunicorn",
              "-w",
              "4",
              "-b",
              "0.0.0.0",
              "--access-logfile=-",
              "app:create_app()",
            ]
          env:
            - name: PYTHONPATH
              value: /myapp
      imagePullSecrets:
        - name: regrobot-dev
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: nancy-staging
spec:
  type: ClusterIP
  selector:
    app: dummyrest
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: myapp-ingress-rule
  namespace: nancy-staging
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.k8s-cluster.nancy.rid-intrasoft.eu
      http:
        paths:
          - backend:
              service:
                name: myapp-service
                port:
                  number: 8000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - tfs.k8s-cluster.nancy.rid-intrasoft.eu
      secretName: secret-tls
